name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '15 8-11 */2  *  *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  push:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rss.lilydjwg.me/zhihuzhuanlan/c_1496496113348206594"
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          max_post_count: 1000
          commit_message: "🔥Update with lastest RadioGeek feed"
          committer_username: "🤖kubbot"
          committer_email: "<>"
          date_format: 'UTC: yyyy-mm-dd'
          template: "$newline #### - [$title]($url) $newline <details><summary>توضیحات</summary> $description </details> $newline <hr /> $newline"
          # Regex for remove HTML TAG:    /(<([^>]+)>)/ig
          item_exec: "post.description = post.description.replace('','')"
          disable_html_encoding: true
