name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '15 8-11 */2  *  *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  push:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.name "openimbot"
          git config --global user.email "openimsdk@qq.com"

      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "My-Blog" 
          feed_list: "https://rss.starerror.com/https://nsddd.top/rss.xml"
          token: ${{ secrets.REDBOT_GITHUB_TOKEN }}
          BOT_GITHUB_TOKEN: ${{ secrets.REDBOT_GITHUB_TOKEN }}
          max_post_count: 100
          commit_message: "🔥docs(main): update with lastest RadioGeek feed"
          committer_username: "openimbot"
          disable_html_encoding: true
      - name: Pull in dev.to zh
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "ZHIHU"
          #feed_list: "https://rss.lilydjwg.me/zhihuzhuanlan/c_1496496113348206594"
          feed_list: "https://rss.lilydjwg.me/zhihuzhuanlan/c_1496496113348206594"
          token: ${{ secrets.REDBOT_GITHUB_TOKEN }}
          BOT_GITHUB_TOKEN: ${{ secrets.REDBOT_GITHUB_TOKEN }}
          max_post_count: 100
          commit_message: "🔥docs(main): update with lastest red zhihu feed"
          committer_username: "openimbot"
          disable_html_encoding: true
